'use client'

import { useState } from 'react'
import { Clipboard, Check } from 'lucide-react'
import type { TestResults } from '@/types'

interface ExportButtonProps {
  results: TestResults
}

export function ExportButton({ results }: ExportButtonProps) {
  const [copied, setCopied] = useState(false)

  function generateReport(): string {
    const { url, task, ux_score, grade, dimensions, summary, recommendations, personas } = results

    let report = `# Phantom UX Report\n`
    report += `**URL:** ${url}\n`
    report += `**Task:** ${task}\n`
    report += `**Score:** ${ux_score}/10 (Grade: ${grade})\n\n`

    report += `## Dimensions\n`
    report += `- Task Success: ${dimensions.task_success}/10\n`
    report += `- Efficiency: ${dimensions.efficiency}/10\n`
    report += `- Clarity: ${dimensions.clarity}/10\n`
    report += `- Error Recovery: ${dimensions.error_recovery}/10\n`
    report += `- Friction Spread: ${dimensions.friction_distribution}/10\n\n`

    if (summary) {
      report += `## Assessment\n${summary}\n\n`
    }

    if (recommendations && recommendations.length > 0) {
      report += `## Recommendations\n`
      recommendations.forEach((rec, i) => {
        report += `${i + 1}. ${rec}\n`
      })
      report += '\n'
    }

    report += `## Persona Results\n`
    for (const p of personas) {
      const status = p.success ? 'Completed' : 'Gave up'
      report += `### ${p.persona_name} — ${status} in ${p.steps_taken} steps\n`
      report += `${p.reason}\n`
      report += `Friction points: ${p.confusion_events.length}\n\n`
    }

    // Accessibility issues
    const allViolations: Array<{ id: string; impact: string; description: string }> = []
    const seenIds = new Set<string>()
    for (const p of personas) {
      for (const v of p.a11y_violations ?? []) {
        if (!seenIds.has(v.id)) {
          seenIds.add(v.id)
          allViolations.push(v)
        }
      }
    }
    if (allViolations.length > 0) {
      report += `## Accessibility Issues\n`
      for (const v of allViolations) {
        report += `- [${v.impact}] ${v.description}\n`
      }
      report += '\n'
    }

    report += `Generated by Phantom — Synthetic UX Testing\n`
    return report
  }

  async function handleCopy() {
    const report = generateReport()
    try {
      await navigator.clipboard.writeText(report)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      // Fallback for older browsers
      const textarea = document.createElement('textarea')
      textarea.value = report
      document.body.appendChild(textarea)
      textarea.select()
      document.execCommand('copy')
      document.body.removeChild(textarea)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    }
  }

  return (
    <div className="flex justify-center pt-2">
      <button
        onClick={handleCopy}
        className="flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-medium transition-all duration-200"
        style={{
          background: 'var(--bg-card)',
          border: '1px solid var(--border-primary)',
          color: copied ? '#10b981' : 'var(--text-secondary)',
        }}
        onMouseEnter={(e) => {
          e.currentTarget.style.background = 'var(--bg-card-hover)'
          e.currentTarget.style.borderColor = 'var(--border-secondary)'
        }}
        onMouseLeave={(e) => {
          e.currentTarget.style.background = 'var(--bg-card)'
          e.currentTarget.style.borderColor = 'var(--border-primary)'
        }}
      >
        {copied ? (
          <>
            <Check size={15} />
            Copied!
          </>
        ) : (
          <>
            <Clipboard size={15} />
            Copy Report
          </>
        )}
      </button>
    </div>
  )
}
